FROM nginx:1.25-alpine
COPY ovhcloud/docker/client/nginx.conf /etc/nginx/nginx.conf
COPY src/front/myb.front/dist/apps/client /usr/share/nginx/html/client
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget --quiet --tries=1 --spider http://localhost/health || exit 1
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
