# Keycloak Secrets

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: myb-platform
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_CLIENT_SECRET: "f4umyKKCMYgaipA3f3MndHeTg8ubvyD2"
  KEYCLOAK_SERVICE_CLIENT_SECRET: "Iae91CtN9N1a3voLVYW4yFsaA7woSTDD"
