export * from './coproperty.component';
export * from './coproperty-list.component';
export * from './coproperty-detail.component';
export * from './dashboard/coproperty-dashboard.component';
export * from './unit-management/unit-management.component';
export * from './charge-distribution/charge-distribution.component';
export * from './owner-management/owner-management.component';
export * from './maintenance-requests/maintenance-requests.component';
export * from './coproperty.routes';
