apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myb-hprd
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  NODE_ENV: "production"

  # Keycloak
  KEYCLOAK_REALM: "MYB"
  KEYCLOAK_CLIENT_ID: "MYB-client"
  KEYCLOAK_SERVICE_CLIENT_ID: "myb-backend"
  KEYCLOAK_MANAGER_ROLE: "coproperty-syndic"
  KEYCLOAK_BASE_URL: "http://keycloak:8080/realms/MYB/protocol/openid-connect"
  KEYCLOAK_AUTHORITY: "http://keycloak:8080/realms/MYB"

  # RabbitMQ (internal service DNS)
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"

  # SMTP → MailHog in HPRD (no real emails sent)
  SMTP_USE_MAILHOG: "true"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"

  # Registry
  REGISTRY: "93pf2bi9.gra7.container-registry.ovh.net/myb"

  TZ: "Europe/Paris"
