FROM nginx:1.25-alpine
COPY ovhcloud/docker/admin/nginx.conf /etc/nginx/nginx.conf
COPY src/front/myb.front/dist/apps/admin /usr/share/nginx/html/admin
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget --quiet --tries=1 --spider http://localhost/admin/ || exit 1
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
