#!/bin/bash
# MYB Coproperty Management - Quick Action Reference
# Generated: February 4, 2026

echo "======================================"
echo "🏢 MYB Coproperty Actions - Quick Ref"
echo "======================================"
echo ""

echo "📱 OWNER PORTAL ACTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "General Assembly (Assemblées Générales)"
echo "  👁️  Voir PV          → viewMinutes(id)          → Download procès-verbal PDF"
echo "  📄  Documents       → viewDocuments(id)        → Download AG documents"
echo "  📅  Calendrier      → addToCalendar(id)        → Download ICS file"
echo ""
echo "Maintenance (Demandes de Travaux)"
echo "  ➕  Nouvelle        → createRequest()          → Open creation modal"
echo "  👁️  Détails         → viewDetails(id)         → Show request details"
echo "  🗑️  Supprimer       → deleteRequest(id)       → Delete (if submitted/acknowledged)"
echo ""

echo "🏗️  SYNDIC PORTAL ACTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Coproperty List (Gestion des Copropriétés)"
echo "  👁️  Détails         → viewDetails(id)         → Navigate to /coproperties/:id"
echo "  ✏️  Modifier        → editCoproperty(id)      → Navigate to /coproperties/:id/edit"
echo "  🔧  Travaux         → manageTravaux(id)       → Navigate with ?tab=maintenance"
echo "  📄  Facture         → createInvoice(id)       → Navigate to /invoices/new?copropertyId=:id"
echo "  🧮  Distribution    → distributeCharges(id)   → Navigate to /distribution?copropertyId=:id"
echo "  🗑️  Supprimer       → deleteCoproperty(id)    → Confirm + cascade delete"
echo ""

echo "🔐 KEYCLOAK USER MAPPING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Login: nidhalbm (Keycloak)"
echo "  ↓"
echo "JWT Token: sub = '550e8400-e29b...'"
echo "  ↓"
echo "DB Query: WHERE KeycloakUserId = '550e8400...'"
echo "  ↓"
echo "Display: Jean Martin (Copropriétaire)"
echo ""
echo "📖 Full docs: docs/USER_MANAGEMENT_ARCHITECTURE.md"
echo ""

echo "📝 TRANSLATIONS STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ coproperty.list.*         17 keys"
echo "  ✅ coproperty.form.*         15 keys"
echo "  ✅ coproperty.owner.*        15 keys"
echo "  ✅ coproperty.unit.*         22 keys"
echo "  ✅ coproperty.charges.*      35+ keys"
echo "  ✅ coproperty.maintenance.*  25+ keys"
echo "  ✅ coproperty.dashboard.*    23 keys"
echo "  ✅ common.*                  25 keys"
echo "  ✅ validation.*              8 keys"
echo ""
echo "  Total: 140+ translation keys"
echo "  Languages: French (fr.json) + English (en.json)"
echo ""

echo "🚀 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start dev server:"
echo "   npx nx serve admin"
echo ""
echo "2. Navigate to:"
echo "   Owner: http://localhost:4201/coproperty/owner/dashboard"
echo "   Syndic: http://localhost:4201/coproperty/syndic/dashboard"
echo ""
echo "3. Test actions:"
echo "   • Owner: Go to Assemblées → Click 'Ajouter au calendrier'"
echo "   • Syndic: Go to Copropriétés → Click action buttons"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📄 IMPLEMENTATION_COMPLETE.md    → Full implementation details"
echo "  🔐 USER_MANAGEMENT_ARCHITECTURE.md → Keycloak + App user mapping"
echo "  ✅ prompt.md                      → Task completion status"
echo ""

echo "======================================"
echo "✅ All features implemented!"
echo "======================================"
